### ISSUE TITLE
reszta

### ISSUE THREAD

**Issue by michalbe** [klasiik/html-template-03#2]
to samo co w 
  [x] https://github.com/klasiik/html-template-02/issues/4
  [x] https://github.com/klasiik/html-template-02/issues/2
  [x] https://github.com/klasiik/html-template-02/issues/5

**Comment by klasiik** [comment]
Favicon dodany

**Comment by klasiik** [comment]
Hover dodany

**Comment by klasiik** [comment]
Hover response dodany
