### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by michalbe** [klasiik/html-template-03#3]
![screen-2015 11 14 22 54 58](https://cloud.githubusercontent.com/assets/347657/11166016/c8d86c26-8b22-11e5-8d97-6d56a6a7208c.png)
tu sie cos rozjechalo na firefoxie (na chrome działa)

**Comment by klasiik** [comment]
U mnie działa normalnie. Zresztą ten obiekt żyje własnym życiem i robi co chce - nie wiem o co mu chodzi.
