### ISSUE TITLE
top stories dynamicznie

### ISSUE THREAD

**Issue by michalbe** [klasiik/html-template-03#4]
Top stories niech generuje sie dynamicznie tak jak  https://github.com/klasiik/html-template-02/issues/6
Weź jakiś duzy tekst z wikipedii, ustaw go jako zmienną tesktową (`String`), podziel go na zdania używając metody `split` i wybieraj losowo po jednym zdaniu jako opis `Top Stories`.

**Comment by klasiik** [comment]
top stories generują się dynamicznie
